### ISSUE TITLE
Error Department Name

### ISSUE THREAD

**Issue by tsksandeep** [sudarshan-reddy/sudarshan-reddy.github.io#1]
### Reason
Back in 2018, I felt very proud when sudarshan said he was an **ECE** graduate because I was also an **ECE** grad. Now suddenly looking at his resume it was written as Computer Science.

### Fix
Change from Computer Science to ECE

### Link
[Sudarshan Resume](https://github.com/sudarshan-reddy/sudarshan-reddy.github.io/blob/master/sudarshan-sept-2019-resume.pdf)

**Comment by sudarshan-reddy** [comment]
@tsksandeep . Thanks!! The resume is outdated, let me update it.
